### ISSUE TITLE
Agent Tasks and Missions for behaivor models

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#117]
## Missions (SMARTS)
* [x] Specify a start and goal position 
* [x] Specify via points #125 (Similar to route intermediaries but at the position level)
* [x] Target speed at specific lanes or intersections (can be implemented with via points: a target point with desired speed )

## Agent vehicle type (SMARTS)
* [x] Support large agent vehicles, such as buses. #126

## Tasks and actions (Both rl agent & OpEn agent)
* [x] U-turn #123 (near a specified vehicle, could be happen anywhere on the road, not just at intersections)
* [x] Cut-in #124 (in front of designated vehicles)
* ~~[ ] Change lane while passing intersection #129~~
* ~~[ ] Occupy 2 lanes~~
* ~~[ ] Overtake(pass) by crossing into the oncoming lane #122~~

This is a meta ticket for the requirements regarding agent tasks and actions. The goal of this issue is to provide agent policies that can accomplish specific tasks and actions.

**DUE: Nov 30**
