### ISSUE TITLE
Replace `HiWayEnv` with "`StandardGymEnv`"

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#1279]
## Description of the issue
`HiWayEnv` as is currently implemented breaks with the `gym` interface in a few locations:
- `reset(..)` can throw an exception due to incompatibility between a scenario and an agent interface.
- `step(..)` returns `dones` individual to agent rather than `done` related the end of an episode
- `observation_space` is not implemented (and must be)
- `action_space` is not implemented (and must be)

## Proposed solution
Create a new standard gym environment that fully conforms to the gym interface. Deprecate `HiWayEnv`.

AC:
- [ ] `reset` is guaranteed to re-initialize a working environment by skipping invalid episode configurations see: https://github.com/huawei-noah/SMARTS/issues/1271#issuecomment-1035879435
- [ ] details should be logged if a scenario&agent-interface combination is invalid to be able to start an episod.
- [ ] `dones` should be returned from `step` instead of `done` and is related to the environment episode being `done` rather than individual agents.
- [ ] consider if #1194 can be integrated to automatically evaluate `action_space` from agent interfaces
- [ ] consider if #1193 can be integrated to automatically evaluate `observation_space` from agent interfaces
- [ ] Deprecate `HiWayEnv`

**Comment by Adaickalavan** [comment]
For reference, currently `/smarts/env/wrappers/format_obs.py` can automatically build the appropriate gym `observation_space` from `agent_specs[agent_id].interface`. This can be used as reference when `adapters` are being worked on.
