### ISSUE TITLE
KS Integration

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#130]
To deliver a better experience of integrating SMARTS with KyberSim: 
- [ ] #403 Customized SMARTS service for KyberSim
- [ ] #78 Minimal SMARTS with only the Core Dependencies
- [ ] #76 Containerized Interaction Scenario Service
- [ ] #382 Option For SMARTS With Limited Influence On SUMO
