### ISSUE TITLE
[Multiple] Fix boid agent observations

### ISSUE THREAD

**Issue by JVillella** [huawei-noah/SMARTS#17]
There are multiple sub-issues here. Just porting this over to GH and keeping original intent.

- [x] OGM and drivable area grid map seem not to be sent to boid agent even if registered in `AgentInterface` (fixed in #22)
- [x] ~~When a vehicle leaves a bubble, a new boid agent is created ("causing inference model to be instantiated again" ~ @Nickniyihan)~~ (likely not an issue from discussion)
- [ ] When a boid agent vehicle goes off road, a new sumo vehicle replace it and is stuck at the road side: #23 
- [x] Boid agent should be created upon vehicle entering, and then sit at top of the bubble and always be there no matter boid agent vehicle traffic: #25

**Comment by JVillella** [comment]
@Nickniyihan 

Regarding,

>OGM and drivable area grid map seem not to be sent to boid agent even if registered in AgentInterface

Seems it's working fine,

![image](https://user-images.githubusercontent.com/6306986/96402389-c1945f80-11a3-11eb-9df1-38aca12c2519.png)

However, Visdom was not visualizing them, but they were being returned. I fixed Visdom visualization and will post a PR shortly.
