### ISSUE TITLE
Mini-City Demo Slice

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#231]
A capstone work that acts both as a good demo and something concrete that can be shown.

### Issues

- #273
- #271
- #269
- #267
- #268

### Optional (Not Triaged)

- [ ] Viewable remotely (Server hosted)
- [ ] Actively training agent (long training agent)
- [ ] Multiple actively training agents in same scenario
- [ ] Additional graphics
- [ ] Mixed traffic simulators (replay mixed with SUMO)
- [ ] Human controlled vehicles
- [ ] Agents/humans can connect on the fly to take over a vehicle in the sim.

**Comment by JVillella** [comment]
Issues I'm noticing so far with a more complex map (not the one presently in this PR):

![image](https://user-images.githubusercontent.com/6306986/100832291-8c7f5c00-3435-11eb-9ee5-cf2c32814da2.png)

---

### Issues/Bugs

<img width="299" alt="Screen Shot 2020-12-02 at 12 25 42 AM" src="https://user-images.githubusercontent.com/6306986/100832110-36aab400-3435-11eb-8826-62bab082fe57.png">

1. Lane dividers (white and yellow lines) are missing in some spots
2. ^ not visible within junctions
3. Getting lots of "Error: Vehicle 'car-flow-random-route-1cd29e68-b057-9f08-85f3-c052cebe89de-4941183041327834838--1-0.0' is not allowed to depart on edge '-307221417#1'"
4. Geometry glitches around some junctions

**Comment by JVillella** [comment]
5. Road caps are round, they should be flat.
![image](https://user-images.githubusercontent.com/6306986/100897443-aea4c880-348d-11eb-9854-8f97dabe5e30.png)
