### ISSUE TITLE
Behavior Model related work

### ISSUE THREAD

**Issue by liamchzh** [huawei-noah/SMARTS#260]
High priority:
- [x] Fix the oscillation and low speed issue of OpEn agent #272
- [x] Tweak u-turn trajectory #222
- [x] Investigation of Lane Change Speed and Curve  #262 (For context please refer to #258)
- [x] Publish OpEn to PyPI #223

Low Priority:
- [ ] Pin bubble to social vehicles #131  
- [ ] Allow specifying a mission with agents captured by bubble
