### ISSUE TITLE
Miscellaneous Envision Tasks

### ISSUE THREAD

**Issue by aurorahcx** [huawei-noah/SMARTS#368]
- [ ] Distorted visualization: https://github.com/huawei-noah/SMARTS/issues/325
- [x] Reconnect SMARTS to Envision: https://github.com/huawei-noah/SMARTS/issues/341
- [ ] Change traffic divider geometries from lines to thin polygons, such that their size can be adjustable and proportional to the viewport 
- [x] Add a collapsible debug panel to display agent's state information #547

**Comment by junluo-huawei** [comment]
closing in favor of the specific issues.
