### ISSUE TITLE
Stable Version of SMARTS

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#399]
This is the driving ticket to reach a final 0.4 version of SMARTS that should act as a stable version users can depend on.

Several areas of concern:
- [x] SUMO
   - [x] TraCI connection error
   - [x] Initial connection to TraCI
   - [x] Internal SUMO errors
- [x] HAC
   - [x] ~gRPC connection proper closing~
   * Wait for user feedback before attempting to address.
- [x] Cleaning logs
   - [x] Make sure the log stdout redirect is closed correctly
   - [x] pybullet log are back :(
   - [x] Clean up logs (again)
- [x] ray
   - [x] check again to see if Workers are closing
- [x] Envision
   - [x] SMARTS side performance
- [ ] Determinism
   - [x] Long running determinism test
      * Needs to be able to work on previous versions of SMARTS if determinism problem is found
- [ ] Test stability on ULTRA training
- [x] SMARTS closes all resources on destroy()
