### ISSUE TITLE
Close Out CoRL Benchmark

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#538]
Finish off the CoRL/MARL Benchmark work.

- [x] Create separate branch from #396 and #161
- [x] Tag branch with CoRL
- [x] Add documentation referencing CoRL branch
- [x] Create wheel and upload to PyPI as smarts-0.4.1X-marl
- [x] Ensure #293, #352, #90 are closed
- [x] Ensure #90, #396 are merged
- [x] Ask @KornbergFresnel to check if CoRL branch is correct

See #293, #396, #352, #90, #161
