### ISSUE TITLE
Large scale RL

### ISSUE THREAD

**Issue by Adaickalavan** [huawei-noah/SMARTS#653]
Issues to address:

- [x] Distributed architecture inspired by [SEED RL](https://ai.googleblog.com/2020/03/massively-scaling-reinforcement.html). 
- [x] SMARTS environment should communicate with social and ego agents via gRPC to send observations and receive actions, instead of via direct function calls. For example, the [`step`](https://github.com/huawei-noah/SMARTS/blob/ea4e5dd93d057ee5b3e1926c884692d555c64906/smarts/env/hiway_env.py#L163) should be controlled over gRPC.
    - [x] Standardize `observation` type and truncate/pad dynamic-length observation variables to fixed lengths. See #691.  
    - [x] Send `observation` to remote social agent via gRPC. See #712 .
    - [x] Receive `action` from remote social agent via gRPC. See #763 .
    - [x] Send/recieve `observation`/`action` to remote ego agent via gRPC. Unify social/ego grpc communication. See #787 .
- [x] Batch `observations` from multiple SMARTS environment before feeding into the learner block, i.e., remote ego agent. See #1087 .
- [ ] Create a SMARTS environment compatible with Tensorflow TF-Agents, by fixing the [HiWayEnv](https://github.com/huawei-noah/SMARTS/blob/proto-dict/smarts/env/hiway_env.py).
- [x] Run distributed SMARTS in server using individual docker containers.

![image](https://user-images.githubusercontent.com/24203326/115644014-d2a56100-a2eb-11eb-966f-d49e750bb3a3.png)

**Comment by Adaickalavan** [comment]
This idea has been superseded by new developments such as 
+ environment wrappers, 
+ new RL examples in the examples folder, and
+ focus on agent zoo.
