### ISSUE TITLE
Heterogeneous Agent Computing

### ISSUE THREAD

**Issue by Gamenot** [huawei-noah/SMARTS#75]
We want 5 social agents all on different machines contributing towards one simulation.

## core
- [x] Seamless hijack of vehicles going through bubbles.
- [x]  A single agent in the simulation from a remote machine
- [x] 5 agents from remote machines

#### prep work
- [x] #88 Merge `Agent` and `Policy`
- [x] #89 `RemoteAgent` to use `async def act(obs)` instead of `send_obs()`, `recv_act()`
- [x] #53   Pool social agents by `agent_specs`.

### networking
- [ ]

**Comment by davidrusu** [comment]
A first implementation completed in #236
